```plantuml
@startuml

participant ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext
participant ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory
participant ch.admin.bj.swiyu.didtoolbox.TdwDeactivator
participant ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryDeactivator
participant ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorStrategy

activate ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext
	ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext -> ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext : deactivate
	activate ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext
		ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext -> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : getDeactivatorStrategy
		activate ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext : getDidMethod
			activate ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext
				ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : ch.admin.bj.swiyu.didtoolbox.model.DidMethodEnum
			deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.TdwDeactivator : builder
			activate ch.admin.bj.swiyu.didtoolbox.TdwDeactivator
				ch.admin.bj.swiyu.didtoolbox.TdwDeactivator --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : ch.admin.bj.swiyu.didtoolbox.TdwDeactivator$TdwDeactivatorBuilder
			deactivate ch.admin.bj.swiyu.didtoolbox.TdwDeactivator
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext : getVerificationMethodKeyProvider
			activate ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext
				ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : ch.admin.bj.swiyu.didtoolbox.VerificationMethodKeyProvider
			deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryDeactivator : builder
			activate ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryDeactivator
				ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryDeactivator --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryDeactivator$WebVerifiableHistoryDeactivatorBuilder
			deactivate ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryDeactivator
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext : getVerificationMethodKeyProvider
			activate ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext
				ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : ch.admin.bj.swiyu.didtoolbox.VerificationMethodKeyProvider
			deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory --> ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext : ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorStrategy
		deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory
		ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext -> ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorStrategy : deactivateDidLog
		activate ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorStrategy
			ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorStrategy --> ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext : java.lang.String
		deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorStrategy
		ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext --> ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext : java.lang.String
	deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext
deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext

@enduml

```
