```plantuml
@startuml

participant ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
participant ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory
participant ch.admin.bj.swiyu.didtoolbox.TdwCreator
participant ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod
participant ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryCreator
participant ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorStrategy

activate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
	ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext -> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : create
	activate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
		ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext -> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : getCreatorStrategy
		activate ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : getDidMethod
			activate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
				ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : ch.admin.bj.swiyu.didtoolbox.model.DidMethodEnum
			deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : allNextKeyHashesDidMethodParameter
			activate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
				ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : java.util.Set
			deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : getDidMethod
			activate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
				ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : ch.admin.bj.swiyu.didtoolbox.model.DidMethodEnum
			deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.TdwCreator : builder
			activate ch.admin.bj.swiyu.didtoolbox.TdwCreator
				ch.admin.bj.swiyu.didtoolbox.TdwCreator --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : ch.admin.bj.swiyu.didtoolbox.TdwCreator$TdwCreatorBuilder
			deactivate ch.admin.bj.swiyu.didtoolbox.TdwCreator
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : getCryptoSuite
			activate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
				ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : ch.admin.bj.swiyu.didtoolbox.vc_data_integrity.VcDataIntegrityCryptographicSuite
			deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : allAssertionMethods
			activate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
				ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext -> ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod : of
				activate ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod
					ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod --> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod
				deactivate ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod
				ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : java.util.Set
			deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : allAuthentications
			activate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
				ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext -> ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod : of
				activate ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod
					ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod --> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod
				deactivate ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod
				ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : java.util.Set
			deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : allUpdateKeysDidMethodParameter
			activate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
				ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : java.util.Set
			deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryCreator : builder
			activate ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryCreator
				ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryCreator --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryCreator$WebVerifiableHistoryCreatorBuilder
			deactivate ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryCreator
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : getCryptoSuite
			activate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
				ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : ch.admin.bj.swiyu.didtoolbox.vc_data_integrity.VcDataIntegrityCryptographicSuite
			deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : allAssertionMethods
			activate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
				ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext -> ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod : of
				activate ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod
					ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod --> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod
				deactivate ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod
				ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : java.util.Set
			deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : allAuthentications
			activate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
				ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext -> ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod : of
				activate ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod
					ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod --> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod
				deactivate ch.admin.bj.swiyu.didtoolbox.model.VerificationMethod
				ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : java.util.Set
			deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : allUpdateKeysDidMethodParameter
			activate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
				ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : java.util.Set
			deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory -> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : allNextKeyHashesDidMethodParameter
			activate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
				ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext --> ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory : java.util.Set
			deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
			ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory --> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorStrategy
		deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogStrategyFactory
		ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext -> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorStrategy : createDidLog
		activate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorStrategy
			ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorStrategy --> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : java.lang.String
		deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorStrategy
		ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext --> ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext : java.lang.String
	deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext
deactivate ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext

@enduml

```
