```plantuml
@startuml

left to right direction
scale 3/4


class ch.admin.bj.swiyu.didtoolbox.Ed25519ProofOfPossessionJWSSignerImpl {
	{method} +supportedJWSAlgorithms () : java.util.Set
}


class ch.admin.bj.swiyu.didtoolbox.Ed25519VerificationMethodKeyProviderImpl {
	{field} #keyPair : java.security.KeyPair
	{field} #provider : java.security.Provider
	{method} +generateSignature ( param[B1 : [B ) : [B
	{method} +getVerificationKeyMultibase () : String
	{method} +isKeyMultibaseInSet ( paramSet1 : java.util.Set ) : boolean
	{method} +writePublicKeyAsPem ( paramFile1 : java.io.File ) : void
}


class ch.admin.bj.swiyu.didtoolbox.InvalidDidLogException {
}


class ch.admin.bj.swiyu.didtoolbox.JCSHasher {
}


class ch.admin.bj.swiyu.didtoolbox.Main {
}


class ch.admin.bj.swiyu.didtoolbox.ProofOfPossessionCreator {
	{method} +create ( paramString1 : String , paramDuration2 : java.time.Duration ) : com.nimbusds.jwt.SignedJWT
}


class ch.admin.bj.swiyu.didtoolbox.ProofOfPossessionCreatorException {
}


interface ch.admin.bj.swiyu.didtoolbox.ProofOfPossessionJWSSigner {
	{method} +getJCAContext () : com.nimbusds.jose.jca.JCAContext
	{method} +sign ( paramJWSHeader1 : com.nimbusds.jose.JWSHeader , param[B2 : [B ) : com.nimbusds.jose.util.Base64URL
}


class ch.admin.bj.swiyu.didtoolbox.ProofOfPossessionVerifier {
	{method} +isValid ( paramSignedJWT1 : com.nimbusds.jwt.SignedJWT , paramString2 : String ) : boolean
	{method} +verify ( paramSignedJWT1 : com.nimbusds.jwt.SignedJWT , paramString2 : String ) : void
}


class ch.admin.bj.swiyu.didtoolbox.ProofOfPossessionVerifierException {
}


enum ch.admin.bj.swiyu.didtoolbox.ProofOfPossessionVerifierException$ErrorCause {
	{field} +EXPIRED
	{field} +FAILED_TO_VERIFY
	{field} +INVALID_NONCE
	{field} +INVALID_SIGNATURE
	{field} +KEY_MISMATCH
	{field} +UNPARSABLE
	{field} +UNSUPPORTED_ALGORITHM
	{field} +UNSUPPORTED_KEY_SUBTYPE
}


class ch.admin.bj.swiyu.didtoolbox.TdwCreator {
	{method} +create ( paramURL1 : java.net.URL ) : String <<deprecated>> 
	{method} +create ( paramURL1 : java.net.URL , paramZonedDateTime2 : java.time.ZonedDateTime ) : String <<deprecated>> 
	{method} +createDidLog ( paramURL1 : java.net.URL ) : String
	{method} +createDidLog ( paramURL1 : java.net.URL , paramZonedDateTime2 : java.time.ZonedDateTime ) : String
	{method} #getDidMethod () : ch.admin.bj.swiyu.didtoolbox.model.DidMethodEnum
}


class ch.admin.bj.swiyu.didtoolbox.TdwDeactivator {
	{method} +deactivate ( paramString1 : String ) : String <<deprecated>> 
	{method} +deactivate ( paramString1 : String , paramZonedDateTime2 : java.time.ZonedDateTime ) : String <<deprecated>> 
	{method} +deactivateDidLog ( paramString1 : String ) : String
	{method} +deactivateDidLog ( paramFile1 : java.io.File ) : String
	{method} +deactivateDidLog ( paramString1 : String , paramZonedDateTime2 : java.time.ZonedDateTime ) : String
	{method} #getDidMethod () : ch.admin.bj.swiyu.didtoolbox.model.DidMethodEnum
}


class ch.admin.bj.swiyu.didtoolbox.TdwDeactivatorException {
}


class ch.admin.bj.swiyu.didtoolbox.TdwUpdater {
	{method} #getDidMethod () : ch.admin.bj.swiyu.didtoolbox.model.DidMethodEnum
	{method} +update ( paramString1 : String ) : String <<deprecated>> 
	{method} +updateDidLog ( paramString1 : String ) : String
	{method} +updateDidLog ( paramFile1 : java.io.File ) : String
	{method} +updateDidLog ( paramString1 : String , paramZonedDateTime2 : java.time.ZonedDateTime ) : String
}


class ch.admin.bj.swiyu.didtoolbox.TdwUpdaterException {
}


interface ch.admin.bj.swiyu.didtoolbox.VerificationMethodKeyProvider {
	{method}  {abstract} +generateSignature ( param[B1 : [B ) : [B
	{method}  {abstract} +getVerificationKeyMultibase () : String
	{method}  {abstract} +isKeyMultibaseInSet ( paramSet1 : java.util.Set ) : boolean
}


class ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext {
	{method} +create ( paramURL1 : java.net.URL ) : String
}


interface ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorStrategy {
	{method}  {abstract} +createDidLog ( paramURL1 : java.net.URL ) : String
	{method}  {abstract} +createDidLog ( paramURL1 : java.net.URL , paramZonedDateTime2 : java.time.ZonedDateTime ) : String
}


class ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorStrategyException {
}


class ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext {
	{method} +deactivate ( paramString1 : String ) : String
	{method} +deactivate ( paramFile1 : java.io.File ) : String
}


interface ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorStrategy {
	{method}  {abstract} +deactivateDidLog ( paramString1 : String ) : String
	{method}  {abstract} +deactivateDidLog ( paramFile1 : java.io.File ) : String
	{method}  {abstract} +deactivateDidLog ( paramString1 : String , paramZonedDateTime2 : java.time.ZonedDateTime ) : String
}


class ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorStrategyException {
}


class ch.admin.bj.swiyu.didtoolbox.context.DidLogUpdaterContext {
	{method} +update ( paramString1 : String ) : String
	{method} +update ( paramFile1 : java.io.File ) : String
}


interface ch.admin.bj.swiyu.didtoolbox.context.DidLogUpdaterStrategy {
	{method}  {abstract} +updateDidLog ( paramString1 : String ) : String
	{method}  {abstract} +updateDidLog ( paramFile1 : java.io.File ) : String
	{method}  {abstract} +updateDidLog ( paramString1 : String , paramZonedDateTime2 : java.time.ZonedDateTime ) : String
}


class ch.admin.bj.swiyu.didtoolbox.context.DidLogUpdaterStrategyException {
}


class ch.admin.bj.swiyu.didtoolbox.jcommander.VerificationMethodParameters {
	{field} +jwk : String
	{field} +key : String
}


class ch.admin.bj.swiyu.didtoolbox.model.DidLogMeta {
	{method} +arePreRotatedUpdateKeys ( paramSet1 : java.util.Set ) : boolean
	{method} +isKeyPreRotationActivated () : boolean
	{method} +isPreRotatedUpdateKey ( paramString1 : String ) : boolean
}


class ch.admin.bj.swiyu.didtoolbox.model.DidLogMetaPeekerException {
}


enum ch.admin.bj.swiyu.didtoolbox.model.DidMethodEnum {
	{field} +TDW_0_3
	{field} +WEBVH_1_0
}


class ch.admin.bj.swiyu.didtoolbox.model.MalformedTdwDidLogMetaPeekerException {
}


class ch.admin.bj.swiyu.didtoolbox.model.MalformedWebVerifiableHistoryDidLogMetaPeekerException {
}


class ch.admin.bj.swiyu.didtoolbox.model.NamedDidMethodParameters {
	{field} +deactivated : Boolean
	{field} +nextKeyHashes : java.util.Set
	{field} +updateKeys : java.util.Set
	{method} +getDidMethodEnum () : ch.admin.bj.swiyu.didtoolbox.model.DidMethodEnum
}


class ch.admin.bj.swiyu.didtoolbox.model.TdwDidLogMetaPeeker {
}


class ch.admin.bj.swiyu.didtoolbox.model.WebVerifiableHistoryDidLogMetaPeeker {
}


class ch.admin.bj.swiyu.didtoolbox.securosys.primus.PrimusEd25519ProofOfPossessionJWSSignerImpl {
	{method} +supportedJWSAlgorithms () : java.util.Set
}


class ch.admin.bj.swiyu.didtoolbox.securosys.primus.PrimusEd25519VerificationMethodKeyProviderImpl {
	{method} +generateSignature ( param[B1 : [B ) : [B
}


class ch.admin.bj.swiyu.didtoolbox.securosys.primus.PrimusKeyStoreInitializationException {
}


class ch.admin.bj.swiyu.didtoolbox.securosys.primus.PrimusKeyStoreLoader {
}


enum ch.admin.bj.swiyu.didtoolbox.securosys.primus.PrimusKeyStoreLoader$SecurosysPrimusEnvironment {
	{field} +SECUROSYS_PRIMUS_HOST
	{field} +SECUROSYS_PRIMUS_PASSWORD
	{field} +SECUROSYS_PRIMUS_PORT
	{field} +SECUROSYS_PRIMUS_USER
}


class ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryCreator {
	{method} +createDidLog ( paramURL1 : java.net.URL ) : String
	{method} +createDidLog ( paramURL1 : java.net.URL , paramZonedDateTime2 : java.time.ZonedDateTime ) : String
	{method} #getDidMethod () : ch.admin.bj.swiyu.didtoolbox.model.DidMethodEnum
}


class ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryDeactivator {
	{method} +deactivateDidLog ( paramString1 : String ) : String
	{method} +deactivateDidLog ( paramFile1 : java.io.File ) : String
	{method} +deactivateDidLog ( paramString1 : String , paramZonedDateTime2 : java.time.ZonedDateTime ) : String
	{method} #getDidMethod () : ch.admin.bj.swiyu.didtoolbox.model.DidMethodEnum
}


class ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryUpdater {
	{method} #getDidMethod () : ch.admin.bj.swiyu.didtoolbox.model.DidMethodEnum
	{method} +updateDidLog ( paramString1 : String ) : String
	{method} +updateDidLog ( paramFile1 : java.io.File ) : String
	{method} +updateDidLog ( paramString1 : String , paramZonedDateTime2 : java.time.ZonedDateTime ) : String
}




ch.admin.bj.swiyu.didtoolbox.Ed25519ProofOfPossessionJWSSignerImpl --|>  ch.admin.bj.swiyu.didtoolbox.Ed25519VerificationMethodKeyProviderImpl
ch.admin.bj.swiyu.didtoolbox.Ed25519ProofOfPossessionJWSSignerImpl ..|>  ch.admin.bj.swiyu.didtoolbox.ProofOfPossessionJWSSigner
ch.admin.bj.swiyu.didtoolbox.Ed25519VerificationMethodKeyProviderImpl ..|>  ch.admin.bj.swiyu.didtoolbox.VerificationMethodKeyProvider
ch.admin.bj.swiyu.didtoolbox.ProofOfPossessionCreator *--  ch.admin.bj.swiyu.didtoolbox.ProofOfPossessionJWSSigner : signer
ch.admin.bj.swiyu.didtoolbox.ProofOfPossessionJWSSigner ..|>  ch.admin.bj.swiyu.didtoolbox.VerificationMethodKeyProvider
ch.admin.bj.swiyu.didtoolbox.ProofOfPossessionVerifierException *--  ch.admin.bj.swiyu.didtoolbox.ProofOfPossessionVerifierException$ErrorCause : errorCause
ch.admin.bj.swiyu.didtoolbox.TdwCreator -->  ch.admin.bj.swiyu.didtoolbox.VerificationMethodKeyProvider : verificationMethodKeyProvider
ch.admin.bj.swiyu.didtoolbox.TdwCreator ..|>  ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorStrategy
ch.admin.bj.swiyu.didtoolbox.TdwDeactivator -->  ch.admin.bj.swiyu.didtoolbox.VerificationMethodKeyProvider : verificationMethodKeyProvider
ch.admin.bj.swiyu.didtoolbox.TdwDeactivator ..|>  ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorStrategy
ch.admin.bj.swiyu.didtoolbox.TdwUpdater -->  ch.admin.bj.swiyu.didtoolbox.VerificationMethodKeyProvider : verificationMethodKeyProvider
ch.admin.bj.swiyu.didtoolbox.TdwUpdater ..|>  ch.admin.bj.swiyu.didtoolbox.context.DidLogUpdaterStrategy
ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext -->  ch.admin.bj.swiyu.didtoolbox.VerificationMethodKeyProvider : verificationMethodKeyProvider
ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorContext -->  ch.admin.bj.swiyu.didtoolbox.model.DidMethodEnum : didMethod
ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext -->  ch.admin.bj.swiyu.didtoolbox.VerificationMethodKeyProvider : verificationMethodKeyProvider
ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorContext -->  ch.admin.bj.swiyu.didtoolbox.model.DidMethodEnum : didMethod
ch.admin.bj.swiyu.didtoolbox.context.DidLogUpdaterContext -->  ch.admin.bj.swiyu.didtoolbox.VerificationMethodKeyProvider : verificationMethodKeyProvider
ch.admin.bj.swiyu.didtoolbox.context.DidLogUpdaterContext -->  ch.admin.bj.swiyu.didtoolbox.model.DidMethodEnum : didMethod
ch.admin.bj.swiyu.didtoolbox.model.DidLogMeta -->  ch.admin.bj.swiyu.didtoolbox.model.NamedDidMethodParameters : params
ch.admin.bj.swiyu.didtoolbox.model.MalformedTdwDidLogMetaPeekerException --|>  ch.admin.bj.swiyu.didtoolbox.model.DidLogMetaPeekerException
ch.admin.bj.swiyu.didtoolbox.model.MalformedWebVerifiableHistoryDidLogMetaPeekerException --|>  ch.admin.bj.swiyu.didtoolbox.model.DidLogMetaPeekerException
ch.admin.bj.swiyu.didtoolbox.securosys.primus.PrimusEd25519ProofOfPossessionJWSSignerImpl --|>  ch.admin.bj.swiyu.didtoolbox.securosys.primus.PrimusEd25519VerificationMethodKeyProviderImpl
ch.admin.bj.swiyu.didtoolbox.securosys.primus.PrimusEd25519ProofOfPossessionJWSSignerImpl ..|>  ch.admin.bj.swiyu.didtoolbox.ProofOfPossessionJWSSigner
ch.admin.bj.swiyu.didtoolbox.securosys.primus.PrimusEd25519VerificationMethodKeyProviderImpl --|>  ch.admin.bj.swiyu.didtoolbox.Ed25519VerificationMethodKeyProviderImpl
ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryCreator -->  ch.admin.bj.swiyu.didtoolbox.VerificationMethodKeyProvider : verificationMethodKeyProvider
ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryCreator ..|>  ch.admin.bj.swiyu.didtoolbox.context.DidLogCreatorStrategy
ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryDeactivator -->  ch.admin.bj.swiyu.didtoolbox.VerificationMethodKeyProvider : verificationMethodKeyProvider
ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryDeactivator ..|>  ch.admin.bj.swiyu.didtoolbox.context.DidLogDeactivatorStrategy
ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryUpdater -->  ch.admin.bj.swiyu.didtoolbox.VerificationMethodKeyProvider : verificationMethodKeyProvider
ch.admin.bj.swiyu.didtoolbox.webvh.WebVerifiableHistoryUpdater ..|>  ch.admin.bj.swiyu.didtoolbox.context.DidLogUpdaterStrategy


@enduml
```
