storage.did.path=./storage/dids

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/docs/openapi.json
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/docs

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

websocket.allowed-origins=*

# Springwolf configuration
springwolf.enabled=true
springwolf.docket.base-package=com.managination.numa.didserver
springwolf.docket.info.title=${spring.application.name:did-server}
springwolf.docket.info.description=DID Server AsyncAPI documentation
springwolf.docket.info.version=1.0.0
springwolf.docket.servers.websocket-server.protocol=ws
springwolf.docket.servers.websocket-server.host=localhost:8080
